; Arquivo de Configuração do Projeto PlatformIO
;
; Opções de compilação: flags de compilação, filtro de origem
; Opções de upload: porta de upload personalizada, velocidade e flags extras
; Opções de biblioteca: dependências, armazenamentos de biblioteca extras
; Opções avançadas: scripts extras
;
; Consulte a documentação para obter mais informações sobre as outras opções e exemplos
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	makuna/RTC@^2.5.0
	adafruit/RTClib@^2.1.4
	locple/LiquidCrystal_I2C_UTF8@^1.2.2
